#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable is not set."
	exit 1
fi

if [ ! -f "$PYFILE" ]; then
	echo "Error: File $PYFILE not found."
	exit 1
fi

filename=$(basename -- "$PYFILE")
filename_no_ext="${filename%.*}"

python -m py_compile "$PYFILE"
mv "__pycache__/$filename_no_ext.cpython-*.pyc" "$filename_no_ext.c"
echo "Compilation successful. Output filename: $filename_no_ext.c"
